### ISSUE TITLE
lists - sorting, selecting, and importing. Various bugs. 

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1076]
**Version:**
 - listmonk: v2.3.0
 - OS: ubuntu

Step 1: 

I created a new list, and sorted by "created". It should be at the top. 
![lists 01](https://user-images.githubusercontent.com/3606996/204967676-4b1e46a6-0c23-48f1-abae-7a21928f5032.jpg)

It's not; it's on page 2:
![lists 02](https://user-images.githubusercontent.com/3606996/204967677-986637c9-842e-4cdf-a368-0616ca246c23.jpg)

Step 2: 

I click "import subscribers". I click in the "lists" box. There should be a popup of all the lists to select from, but there's not:
![lists 03](https://user-images.githubusercontent.com/3606996/204967679-468d657c-df42-45a9-a5a2-ecdb3a4cfefe.jpg)

Step 3: 

I click the "x" to remove the current list:
![lists 04](https://user-images.githubusercontent.com/3606996/204967683-fb19bf13-9d96-4b7e-a2d1-df01594551b0.jpg)

Step 4: 

I click in the box again, and only the one list shows up. 
![lists 05](https://user-images.githubusercontent.com/3606996/204967674-5b6551ba-379c-49fc-9e30-790a87739db6.jpg)

Step 5: 

After importing them, it still doesn't show the other lists for me to add them to:
![lists 06](https://user-images.githubusercontent.com/3606996/204969045-44ad3c16-7d92-49fc-a75e-604e02487206.jpg)

When I navigated to the "import subscribers" page /admin/subscribers/import, still only that one list would show up. 

I instead navigated to it by clicking "import subscribers" on another list, and all the lists **except** that one showed up. 

If I open a new tab and navigate to the "import subscribers" page /admin/subscribers/import, everything shows up. **BUT** if I first go to "lists" /admin/lists and sort by "created", the same bug happens with the list being on the 2nd page, then not showing up at all on /admin/subscribers/import. 

After separately importing the same list of 500 subscribers to the other list I wanted to add them to, the "Next 03-500" list now displays at the top of page 1 when sorting by "created". 

UPDATE:

The next day, for the new list (Next 04), it was similar, but on Step 2 only the "next all" list showed up when clicking in the box, which is the 2nd list I was trying to add the previous one to (and which I did add it to). And after successful import, and sorting by "newest created" it's still on page 2. 

It is also not in the list at all on my campaign page /admin/campaigns/40 where I'm trying to select a list to send the campaign to.

**Comment by knadh** [comment]
1) Sorting is fixed.

2) Confused about what's happening with the popup list. Once lists are created, the import page has to be refreshed once (if it was left open) for it to be fetched again. Also, a list that has already been selected will not show in the popup again, so if there's only one list, and it's already selected, there will be no popup.

**Comment by MaximilianKohler** [comment]
2. I suspect it may have been fixed by the sorting fix. But an easy way to demonstrate the bug is to search one list name. If only that one list shows up in the results, it will then be the only list that gives a result on the "import subscribers" and "campaign" pages (in the boxes you click on to select a list). 

Easy fix is refreshing the page.

**Comment by MaximilianKohler** [comment]
There are even benefits to the current behavior (_easy/quick access to the specific lists you want_), so I wouldn't mind it staying as is.

**Comment by MaximilianKohler** [comment]
> 1. Sorting is fixed.

`/admin/subscribers/lists/152` if you click on "status" it doesn't sort by unsubscribed and blocklisted. 

`/admin/lists` if you click on "subscribers" it doesn't sort accurately.

**Comment by MaximilianKohler** [comment]
@knadh could you reopen this issue due to my last comment on April 7?

**Comment by knadh** [comment]
Looks like these got fixed at some point. Sorting in the above two scenarios work correctly on the latest version.

**Comment by MaximilianKohler** [comment]
I'm on the latest version (v2.5.1) and still experiencing it:

![subs sort 1](https://github.com/knadh/listmonk/assets/3606996/9f5d16a6-a4f9-4575-84b9-c546157b710a)
Reversed:
![subs sort 2](https://github.com/knadh/listmonk/assets/3606996/2b29f84c-0e44-4895-8387-8c248df50e84)
Last page (15):
![page 15](https://github.com/knadh/listmonk/assets/3606996/3ccfae54-aec2-4b3c-9cb2-b029794fa842)
![sort by status 1](https://github.com/knadh/listmonk/assets/3606996/8fbacc85-fdc9-4def-a83b-8085997daab3)
Reverse status:
![reverse sort](https://github.com/knadh/listmonk/assets/3606996/4260693e-ee90-4667-aa10-384ed881d651)

**Comment by knadh** [comment]
Ah, this turned out to be quite tricky. Don't know how I missed this earlier. Fixed now in https://github.com/knadh/listmonk/commit/c59825f3a5f4c4ccaac25e2d57b19a4e3084d1df

Thanks for illustrating the issue in detail @MaximilianKohler

**Comment by MaximilianKohler** [comment]
Hey knadh, thanks for all the recent updates! I just noticed that in `/admin/lists` I created a list named `test2` and when I search for `test` I can't find it. It only shows if I type in `test2`. It looks like the search only recognizes whole words. IE: `test` does show `test-list ` and `bounce-test-list `.
