### ISSUE TITLE
Defining volume for uploads via docker-compose

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#113]
I'm trying to setup a path for uploads for media and defined the following in my docker-compose.

listmonkapp:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    container_name: listmonkapp
    ports:
      - 8000:9000
    volumes:
      - /mnt/data/listmonk-data/config.toml:/listmonk/config.toml
      - /mnt/data/listmonk-data/uploads:/listmonk/uploads/

I can get the file to upload this way, but then when I try to view the file, I get a nginx 404 error.
My nginx config looks like this:

 location /uploads {
        include  /etc/nginx/mime.types;
        root /home/listmonk;
        gzip_static on;
    }

and my config.toml looks like this:

[upload.filesystem]
        # Path to the uploads directory where media will be uploaded.
        upload_path="./uploads"

        # Upload URI that's visible to the outside world.
        # The media uploaded to upload_path will be made available publicly
        # under this URI, for instance, list.yoursite.com/uploads.
        upload_uri = "/uploads"

Maybe I'm just tired, but I'm not seeing how to get this working. Can you help?

**Comment by knadh** [comment]
Your Nginx conf says `/home/listmonk` while the mount path is just `/listmonk`. That could be why. Can you try removing `/home` from your Nginx path?

**Comment by cb3inco** [comment]
No luck. :(

**Comment by mr-karan** [comment]
Is the nginx running on host (non containerised) ? ---- On Tue, 26 May 2020 00:24:01 +0530  notifications@github.com  wrote ----
No luck. :(

**Comment by cb3inco** [comment]
No - nginx is containerized as I'm running some other apps as well.

**Comment by mr-karan** [comment]
So, just trying to understand the environment you have. How does the volume binding in listmonk container gets translated on the nginx container? Can you show the mount points? Additionally, can you go inside nginx container and confirm the path to `root` you've given, does indeed contain those uploaded files? A simple `ls` output is enough.  ---- On Tue, 26 May 2020 00:27:49 +0530  notifications@github.com  wrote ----
No - nginx is containerized as I'm running some other apps as well.

**Comment by cb3inco** [comment]
Ok, I got it working. In my config.toml I modified the path to be /media/uploads and now it's loading images correctly. So as follows.

My docker-compose file mounts:

listmonkapp:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    container_name: listmonkapp
    ports:
      - 8000:9000
    volumes:
      - /mnt/data/listmonk-data/config.toml:/listmonk/config.toml
      - /mnt/data/listmonk-data/uploads:/listmonk/uploads

My nginx config file:

 root /;

    location / {
        # Protect all routes by default with basicauth.
        auth_basic "login";
        auth_basic_user_file conf.d/.htpasswd;

        proxy_pass http://listmonk;
    }

    # Public endpoints that should not be behind auth.
    location /subscription {
        proxy_pass http://listmonk;
    }

    location /link {
        proxy_pass http://listmonk;
    }

    location /uploads {
        include  /etc/nginx/mime.types;
        root /;
        gzip_static on;
    }

and my config.toml file

 [upload.filesystem]
 
# Path to the uploads directory where media will be uploaded.
upload_path="./uploads"

# Upload URI that's visible to the outside world.
# The media uploaded to upload_path will be made available publicly
# under this URI, for instance, list.yoursite.com/uploads.
upload_uri = "/media/uploads"


**It appears that I can put anything in /anythingIwant/uploads** to make it work. I think my brain is to tired to try to understand why /uploads won't work with the above configuration. Uploading files worked fine with just /uploads but it would not display the images.

**Comment by mr-karan** [comment]
Cool. Hope the issue is fixed then :+1:

**Comment by cb3inco** [comment]
Actually this isn't fixed. I can't access any images from the world as I get a 404. I think my problem is I don't know the path that the container is expecting the images to be in.

For example I have - /mnt/data/listmonk-data/uploads:/listmonk/uploads in my docker-compose, but is :/listmonk/uploads correct? It's behaving that is not correct.

**Comment by mr-karan** [comment]
Okay, a bit confused since you'd mentioned

> Ok, I got it working. In my config.toml I modified the path to be /media/uploads and now it's loading images correctly.

Like I previously said, show your complete mount points on Nginx and `ls` output of the `root` directory you are giving. I have a feeling you are not mounting the listmonk uploads volume to the nginx container, hence the 404.

**Comment by cb3inco** [comment]
I'm sorry. Your mention of the nginx mount tipped it off for me. I'm not able to see the images publicly. Sorry about the hassle. Didn't mean to be a pain. Is there any other mounts I need to add to my nginx config, or just the one for /uploads?

**Comment by knadh** [comment]
@cb3inco could you please share your Nginx Docker config? Difficult to guess.

**Comment by cb3inco** [comment]
@knadh - I did get this sorted out. Thanks for your help.

**Comment by satoshinotdead** [comment]
> @knadh - I did get this sorted out. Thanks for your help.

May I know how you figured it out?  I'm trying to get the same using Nginx reversed proxy with docker compose on Listmonk.
