### ISSUE TITLE
Problems running on Docker

### ISSUE THREAD

**Issue by cgobbet** [knadh/listmonk#390]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: Mac Big Sur 11.04

**Description of the bug and steps to reproduce:**
I've installed Listmonk on my Mac around two months ago, and after some back and forth, it has worked well. Today I tried to run it again, but a weird thing happened. First, it ran normally, but the DB was a different one, without any history, campaigns, subscribers, nothing. After re-starting, when I launched it via Terminal, the response was an error message:

```
[MACHINE NAME] com.docker.docker >> docker compose up
[+] Running 4/0
 ⠿ Container comdockerdocker_demo-db_1   Running                                                                    0.0s
 ⠿ Container comdockerdocker_demo-app_1  Running                                                                    0.0s
 ⠿ Container comdockerdocker_db_1        Created                                                                    0.0s
 ⠿ Container comdockerdocker_app_1       Created                                                                    0.0s
Attaching to app_1, db_1, demo-app_1, demo-db_1
Error response from daemon: driver failed programming external connectivity on endpoint comdockerdocker_db_1 (e2dcf5fd40f60311c43f2f5ca5177bc474eb0b69afd3805e942c5082af0ceb52): Bind for 0.0.0.0:9432 failed: port is already allocated
```
When I checked on Docker, I saw that there were duplicated instances of Listmonk and Postgres, which I could not remove anyhow:

![Screenshot 2021-06-10 at 14 50 11](https://user-images.githubusercontent.com/4549818/121530556-d3aa6300-c9fd-11eb-934b-51e608fb4433.png)

Could you help me to understand what am I doing wrong? Losing the history of the campaigns would be such a pain.

@mr-karan , I am adding you here following a conversation with Kailash.

Thanks in advance

**Comment by Loocos** [comment]
Hi @cgobbet,

Did you follow these instructions ? https://listmonk.app/docs/installation/#production
That's because you're running both demo and production containers

**Comment by cgobbet** [comment]
Hi, @Loocos , yes, I followed the Production setup instructions. I tried the demo many months ago and on a different machine. In this one, I did not. I wonder if it's possible that some folder from the demo install had migrated to my new machine, but it's very unlikely, as I imported virtually everything manually.

What should I do in this case?

**Comment by Loocos** [comment]
The error say : Bind for 0.0.0.0:9432 failed: port is already allocated
I already meet this problem at the beginning. For me, you should stop every containers and do that :
- docker-compose down
- docker-compose up -d db
- if u never run this command, execute it : docker-compose run --rm app ./listmonk --install
- docker-compose up -d app

You should be able to connect to http://localhost:9000

**Comment by cgobbet** [comment]
I will do that, @Loocos , but just one question: using the "install" command will not replace the data from my previous activity. Is that correct? And I should run it from the same Terminal window I am using ("com.docker.docker"). 

Is that correct?

**Comment by Loocos** [comment]
If you have already run listmonk and use it with a previous version. I'm not sure, but I think yes, you will lost the data.
In that case, you must use : docker-compose run --rm app ./listmonk --upgrade
In order to upgrade your current DB.

Yes in the same terminal in the working directory where you've have your  docker-compose yaml file.

**Comment by cgobbet** [comment]
@Loocos I followed the instructions, but after the `docker-compose run --rm app ./listmonk --upgrade` command, I receive the error message below:
```
[MACHINE NAME] com.docker.docker >> docker-compose run --rm app ./listmonk --upgrade
Creating comdockerdocker_app_run ... done
2021/06/10 13:59:31 main.go:84: v1.1.0 (b361292 2021-06-09T14:49:25Z)
2021/06/10 13:59:31 init.go:99: reading config: config.toml
2021/06/10 13:59:31 init.go:190: connecting to db: localhost:5432/listmonk
2021/06/10 13:59:31 init.go:193: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused
ERROR: 1
```
Plus, the extra images are still on Docker (I don't know if they should have been removed after the process).

Pls tell me what to do next and thanks!

**Comment by Loocos** [comment]
Ok! Great. Now, you have to edit your config.toml (if u don't have it, please create it following the documentation).
Edit the [DB] part, and set the host to db (the docker container name of your postgre sql)

docker-compose down
then 
docker-compose up -d

It should works :)

**Comment by cgobbet** [comment]
Ok, so should I add that part of code just below the `app` line. Is that correct? I should not delete anything, right?

**Comment by Loocos** [comment]
Of course no

**Comment by cgobbet** [comment]
Added it to the docker-compose.yml:
 ```
 app:
    <<: *app-defaults
    depends_on:
      - db
    volume:
    - ./path/on/your/host/config.toml/:/listmonk/config.toml
```
But when I run `docker-compose down`, I get the message:

```
[MACHINE NAME] com.docker.docker >> docker-compose down
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.app: 'volume' (did you mean 'volumes'?)
```

**Comment by mr-karan** [comment]
As the error message says, rename `volume` to `volumes`.

**Comment by cgobbet** [comment]
Hi, the `docker-compose down` worked flawlessly, but the following command still gives me an error:
```
[MACHINE NAME] com.docker.docker >> docker-compose up -d
Creating network "comdockerdocker_listmonk" with the default driver
Creating comdockerdocker_demo-db_1 ... 
Creating comdockerdocker_db_1      ... 
Creating comdockerdocker_db_1      ... error

ERROR: for comdockerdocker_db_1  Cannot start service db: driver failed programming external connectivity on endpoint comCreating comdockerdocker_demo-db_1 ... done
is already allocated
Creating comdockerdocker_demo-app_1 ... done

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint comdockerdocker_db_1 (a15e90a08d57802f41942846cad1052deb6e9f40a9d9e7f1f0d28b2b90b6d7f8): Bind for 0.0.0.0:9432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

Thanks in advance!

**Comment by mr-karan** [comment]
Please read the instructions carefully mentioned here: https://listmonk.app/docs/installation/#production

You need to spin up containers with `docker-compose up app db` **only**. Doing `docker-compose up -d` will spin up the demo instances as well as prod containers, which is causing the issue.

**Comment by cgobbet** [comment]
Thanks @mr-karan . I will follow the instructions from scratch, which I presume will make a fresh install. Three quick questions:

1) the current install with my data (campaign, subscribers, templates, etc) will all be deleted, right?
2) should I remove manually the images or containers that remain on Docker?

**Comment by mr-karan** [comment]
If you were running the DB container with the volume mount then the data won't be deleted. 

Just do `docker-compose down`. This will stop all running containers. Doesn't effect the volumes. 

Then do `docker-compose up app db`. This will run the DB with the same volume as previously.

**Comment by cgobbet** [comment]
Ok: going with `docker-compose down` works, all containers stop. I went through the whole install listed [here](https://listmonk.app/docs/installation/#production). When I use the `docker-compose up db`, It stays locked then at this message:
```
[MACHINE NAME] com.docker.docker >> docker-compose up db
Starting comdockerdocker_db_1 ... done
Attaching to comdockerdocker_db_1
db_1        | 
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        | 
db_1        | 2021-06-10 15:10:13.318 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2021-06-10 15:10:13.318 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2021-06-10 15:10:13.351 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2021-06-10 15:10:13.427 UTC [27] LOG:  database system was shut down at 2021-06-10 15:09:59 UTC
db_1        | 2021-06-10 15:10:13.465 UTC [1] LOG:  database system is ready to accept connections
```
I presume this state is expecting another input, because it becomes non-responsive. What to do next?

Thanks

**Comment by mr-karan** [comment]
Yep it's working as expected. 
Open another terminal and run the next command. It'll run schema migrations. But beware running --install will wipe your DB. If that's how you want to proceed. 

Then you can go back to the other terminal, exit out of the running DB container and run `docker-compose up -d app db`

**Comment by cgobbet** [comment]
It went through. I presume now I should run:

`docker-compose down`
then
`docker-compose up -d`

Is that correct?Thanks for the availability

**Comment by cgobbet** [comment]
First to all of you, thanks for the availability.

Ok, I did it:
```
[MACHINE NANE] com.docker.docker >> docker-compose up -d db app
comdockerdocker_db_1 is up-to-date
Starting comdockerdocker_app_1 ... done
```
Now the command to run is `docker-compose up app`. Is that correct?

**Comment by knadh** [comment]
> Now the command to run is docker-compose up app. Is that correct? I mean no docker-compose down or anyone else, right?

Nothing else is need. You are already running the app with the previous command. `-d` in the command means "detach" and run the apps behind the scenes. No need to run `up` again after that. You can access listmonk on `http://localhost:9000`.

When you run apps without `-d`, they run on the foreground on the terminal and get killed when you close the terminal.

**Comment by mr-karan** [comment]
> error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused

The config.toml should have the DB host as `db`.  It's connecting to 127.0,0.1, because I think that's what you gave in config.toml there. Once you edit it you can run `docker-compose up -d db app` again.

**Comment by cgobbet** [comment]
Fine, so i must input the path to the `docker-compose.yml `containing the config-toml code. Is it something like this?
`./Users/[machine name]/Library/Containers/Docker/config.toml/:/listmonk/config.toml `

**Comment by mr-karan** [comment]
Yep, that's correct, You can checkout the contents of `config.toml` to put here from the sample file; https://github.com/knadh/listmonk/blob/master/config.toml.sample

P.S. If you've never done these steps before, then it indeed means you were running demo setup for many months. The docs say that demo setup has no persistence, so I think all your data is lost anyway.

**Comment by cgobbet** [comment]
I am missing something, as the path I am using is not correct and giving me an error message:

```
[MACHINE NAME] com.docker.docker >> docker-compose up -d db app
Removing comdockerdocker_app_1
comdockerdocker_db_1 is up-to-date
Recreating 42fb17f2938e_comdockerdocker_app_1 ... error

ERROR: for 42fb17f2938e_comdockerdocker_app_1  Cannot start service app: Mounts denied: approving /Users/[MACHINE NAME]/Library/Containers/com.docker.docker/Users/[MACHINE NAME]/Library/Containers/Docker/config.toml: file does not exist

ERROR: for app  Cannot start service app: Mounts denied: approving /Users/[MACHINE NAME]/Library/Containers/com.docker.docker/Users/[MACHINE NAME]/Library/Containers/Docker/config.toml: file does not exist
ERROR: Encountered errors while bringing up the project.
```

I notice that the response brings the path twice, so the error is problem of syntax. in the `docker-compose.yml` file, I am using the path from `Users` until the folder where the `yml` file is. What I am not doing right?

Thanks in advance

**Comment by mr-karan** [comment]
Ahh. Docker in macOS runs inside a VM so it needs to whitelist some specific directories for the mounts to work. 

Maybe you can take a look at https://docs.docker.com/docker-for-mac/. I don't have access to macOS so can't debug much here.

**Comment by cgobbet** [comment]
Thanks @mr-karan @knadh @Loocos for the availability. I will re-install everything from scratch. I have the data that I possibly lost saved elsewhere. It will take me more time to investigate than install it properly. But thanks anyway.

PS: have you even considered create a Listmonk version to be installed on NAS's like Asustor? It would be great! Thanks again

**Comment by mr-karan** [comment]
I'm not familiar with it. Saw the [App Central](https://www.asustor.com/app_central/app_detail?id=1106&type=9&model=) but didn't find more information on how to put apps there. 

Anyway if this NAS gives a Linux terminal to you, the installation docs will work out of the box.

Additionally, I'll work on a one liner command which makes the installation process of listmonk simpler as the current docs/setup does assume some kind of Docker knowledge as a per-requisite. :smile:

**Comment by cgobbet** [comment]
@mr-karan That will be awesome! I will take a look at the Linux option!

Thanks a lot!

**Comment by cgobbet** [comment]
Hello. As I said, I started from scratch, both Docker and Listmonk. I whitelisted the folder where Docker is and did the install by the book, production-inly, no demo commands.

When I run, `docker-compose run --rm app ./listmonk --install` I get this error:
```
[MACHINE NAME] Docker >> docker-compose run --rm app ./listmonk --install
Creating docker_app_run ... done
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/[MACHINE NAME]/Library/Containers/Docker/path/on/your/host/config.toml" to rootfs at "/listmonk/config.toml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: 1
```
The .toml path is correct, but when I run the code above, I notice a folder is created at the same dir as the `docker-compose.yml` file, with many folders inside, where each one corresponds to one level of the path I've written on the `config.toml` file

Any insights? if not, I will wait for @mr-karan one-line magic :-)

**Comment by mr-karan** [comment]
Ah, I spotted another typo in the docs. :sweat_smile: Before fixing the docs, can you try:

```
volumes:
    - ./path/on/your/host/config.toml:/listmonk/config.toml
```

Notice, the docs have `.toml/:/`. There's an extra `/` after `.toml` which makes it look like a directory. So, `.toml:/listmonk/config.toml` should fix it.

**Comment by cgobbet** [comment]
Still an issue:

```
[MACHINE NAME] Docker >> docker-compose run --rm app ./listmonk --install
Creating docker_app_run ... done
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/[MACHINE NAME]/Library/Containers/Docker/Users/[MACHINE NAME]/Library/Containers/Docker/config.toml" to rootfs at "/listmonk/config.toml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: 1
```
When I run the command, it creates folders with names following the path I gave to the `docker-compose.yml`, even if the folder `config.toml` is there.

**Comment by cgobbet** [comment]
I am still getting an error message:

```
[MACHINE NAME] Docker >> docker-compose up app db
Removing docker_app_1
docker_db_1 is up-to-date
Recreating cfa085e1ba93_docker_app_1 ... error

ERROR: for cfa085e1ba93_docker_app_1  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/[MACHINE NAME]/Library/Containers/Docker/Users/[MACHINE NAME]/Library/Containers/Docker/config.toml" to rootfs at "/listmonk/config.toml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/Users/[MACHINE NAME]/Library/Containers/Docker/Users/[MACHINE NAME]
![Screenshot 2021-06-13 at 12 42 13](https://user-images.githubusercontent.com/4549818/121804120-1f9b1900-cc45-11eb-9125-d1ab876e4938.png)
/Library/Containers/Docker/config.toml" to rootfs at "/listmonk/config.toml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```
AS A byproduct, I have these folders  being created in the directory with the names I provide in the path (screenshot attached)
![Screenshot 2021-06-13 at 12 42 13](https://user-images.githubusercontent.com/4549818/121804166-4fe2b780-cc45-11eb-9689-9fb4cd2c95ed.png)

**Comment by mr-karan** [comment]
Something wrong going in your environment here. I just tried this:

```yml
  app:
    <<: *app-defaults
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
```

Directory structure:

```sh
/tmp/listmonk 
❯ ll
total 8.0K
-rw-r--r--. 1 karan karan 270 Jun 13 19:13 config.toml
-rw-r--r--. 1 karan karan 916 Jun 13 19:15 docker-compose.yml
```

And it worked without issues.

**Comment by cgobbet** [comment]
Ok, I uninstalled Docker completely and installed it again. I did the install by the book and it worked until the last step (including the comfig.toml showed above in the docker-compose-yml). The `postgres` container runs fine but when I look for the listmonk container under `comdockerdocker`, I see there are two of them:

<img width="496" alt="Screenshot 2021-06-13 at 21 26 07" src="https://user-images.githubusercontent.com/4549818/121819554-fbaff580-cc8d-11eb-93c5-f3802ef3bd5d.png">

Inspecting it on Docker, It keeps restarting with the following error message:

`2021/06/13 19:09:13 init.go:193: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused`

I cannot also see the `tmp` folder mentioned above. Should it be in the Docker folder too? My Docker folder has just a `Data` folder and the `yml` file

**Comment by rizwan95** [comment]
Even I face the same issue when a config.toml file path is explicitly specified in the docker-compose.yml file

**Comment by mr-karan** [comment]
> connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused

https://github.com/knadh/listmonk/issues/390#issuecomment-859390957

**Comment by mr-karan** [comment]
> Even I face the same issue

what issue?

**Comment by rizwan95** [comment]
> > Even I face the same issue
> 
> 
> 
> what issue?

This one -> connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by cgobbet** [comment]
@knadh @mr-karan I kept tweaking the config here, but the outcome is always the same: the container `comdockerdocker` has two instances inside: postgres (named `comdockerdocker_db_1`) and listmonk (named `3693872b21a3_comdockerdocker_app_1`) Postgres seem to rule just fine, but the Listmonk starts, fails with the following error message:

```
3693872b21a3_comdockerdocker_app_1 exited with code 1
3693872b21a3_comdockerdocker_app_1 | 2021/06/15 12:23:51 main.go:84: v1.1.0 (b361292 2021-06-09T14:49:25Z)
3693872b21a3_comdockerdocker_app_1 | 2021/06/15 12:23:51 init.go:99: reading config: config.toml
3693872b21a3_comdockerdocker_app_1 | 2021/06/15 12:23:51 init.go:190: connecting to db: localhost:5432/listmonk
3693872b21a3_comdockerdocker_app_1 | 2021/06/15 12:23:51 init.go:193: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused
```

A curious note: the struggling Listmonk instance tries to restart always on port `9000`, but the error comes from a refused connection on port `5432`

I'll be waiting for further advice from you. Thanks!

**Comment by Loocos** [comment]
@cgobbet I already gave you the solution for that error
error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused

If you've kept the original config, you must change your config.toml (host of db part = db) : 
![image](https://user-images.githubusercontent.com/26056280/122054333-df27d080-cde7-11eb-9bfa-dc15b6eb06e1.png)

Why I've changed the host value by db ? Because docker is able to resolve the ip of the  container by his hostname. In this project, the postgre database is called db.

**Comment by mr-karan** [comment]
Let's wait for https://github.com/knadh/listmonk/pull/394 to get merged. 

I am not sure about macOS since, in macOS you need to whitelist some file paths for Docker to access it (as it's inside a VM), but this easy install script should pretty much work on most *nix environments.

**Comment by knadh** [comment]
#394 is merged.

**Comment by cgobbet** [comment]
ok, I did evrything again, and process goes smooth (thanks @mr-karan) until `docker-compose run --rm app ./listmonk --install`. It then brings the error:
```
[MACHINE NAME] listmonk >> docker-compose run --rm app ./listmonk --install
Creating listmonk_app_run ... done
Error response from daemon: Mounts denied: approving /Users/[MACHINE NAME]/Library/Containers/com.docker.docker/listmonk/config.toml: file does not exist
ERROR: 1
```
However, the files *are* within the `listmonk` folder [see screenshot](https://i.imgur.com/e6dflKS.png). Sorry for insisting so long, but I can't give up...

**Comment by mr-karan** [comment]
Yeah like I said in https://github.com/knadh/listmonk/issues/390#issuecomment-861474605, the error  `Mounts denied: approving` this basically means this path is not whitelisted in Docker Mac app.

**Comment by cgobbet** [comment]
Two levels of directory white-listed. Is this the right place? I restarted Docker twice, to no avail...

![Screenshot 2021-06-15 at 17 39 49](https://user-images.githubusercontent.com/4549818/122083154-e5767680-ce00-11eb-870f-4d38aa766c57.png)

**Comment by mr-karan** [comment]
This shell script creates a file in the current working directory from where the shell script is executed. So the correct place to whitelist is the location from where you're executing the script itself. 

I don't have a macOS environment to test this but maybe someone can look into this.

**Comment by cgobbet** [comment]
Ok, guys, that's my last one;

I got pissed that the thing was not working, that I did a Docker re-install from scratch - again - and tested all alternatives until it worked.

This time, for this to work, I went through all steps, including the `Getting Ready` tutorial (which I had done in the past) to leave nothing aside.

For me, I guess the problem was the directory place. Earlier, I was starting the process from the `Docker` folder within `Library`. It is not written anywhere that's should be there, but there is no indication otherwise too. This time, as I ran the `Getting Started` tutorial, I started on my user folder. From there, I followed the instructions on the documentation.

For me, using the shell script didn't work. I got this error:

cassiano ~ >> sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"

```
> fetching config.toml from listmonk repo
> fetching docker-compose.yml from listmonk repo
> generating a random password
tr: Illegal byte sequence
> modifying config.toml
sed: 1: "config.toml": command c expects \ followed by text
```

...so I used the `Docker` command to pull `Listmonk` and then, from there, I edited `config.toml` accordingly and the following steps worked. Following my experience, I'd say that having the same instructions everywhere (now between the repo, the site page and the Docker site page have small differences) would be very helpful. Telling exactly where the directory should be (or where it should _not_ be) would add a layer of safety to the process.

Thanks to all of you for your availability. :-)

**Comment by mr-karan** [comment]
> Earlier, I was starting the process from the Docker folder within Library. It is not written anywhere that's should be there, but there is no indication otherwise too

the first line `mkdir listmonk` indicates it's better to keep a separate folder, which will contain the config file, docker-compose file etc. https://github.com/knadh/listmonk/#easy-docker-install
_But_ You can use any directory in any *nix system, it doesn't matter. For macOS specifically it matters, hence I told in this thread multiple  times that's the case.

> For me, using the shell script didn't work. I got this error:

This again looks like a macOS issue where `tr` doesn't run as expected: https://unix.stackexchange.com/questions/141420/tr-complains-of-illegal-byte-sequence.

> Following my experience, I'd say that having the same instructions everywhere (now between the repo, the site page and the Docker site page have small differences) would be very helpful.

Yep, I agree. That was a miss on my parts. The docs are more clear than they should have been, thanks to this issue :) https://github.com/knadh/listmonk-site/pull/18

> Thanks to all of you for your availability. :-)

No worries. Installation shouldn't be this hard and thanks to you and this thread specifically, listmonk's install process got a little better than what it was before. 

I'd say just downloading the listmonk binary and running a Postgres server on Mac would have been a better experience, if you're willing to consider that: https://listmonk.app/#download :+1:

**Comment by cgobbet** [comment]
Thanks, Karan. The binary demands Docler anyway, right? And no problems about anything. You have been really good in customer care. I hope I'll be as good as you doing that someday. Have a great day for all the @listmonk team.

**Comment by mr-karan** [comment]
> The binary demands Docler anyway, right?

Nope. The binary is standalone, no dependencies. Instructions to setup here: https://listmonk.app/docs/installation/#binary

You just need a working Postgres server, which I believe you can just use: https://postgresapp.com/ on macOS.

**Comment by humblecoder** [comment]
@mr-karan with regard to @cgobbet's `tr: Illegal byte sequence` issue, what about changing

```echo $(tr -dc A-Za-z0-9 < /dev/urandom | head -c 13 ; echo '')```

to something like

```echo $(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 13 ; echo '')```

Seems to fix the issue on MacOS, and doesn't break anything in Linux (as far as I can tell)

**Comment by cgobbet** [comment]
Thanks, @mr-karan but as it is working without the turnaround, I won't mess with it. 😃

question: do you guys think about preparing the installation package for NAS devices? I'd definitely would like that.

Have a great day!
