### ISSUE TITLE
Capturing abuse reports from SES and other providers

### ISSUE THREAD

**Issue by binaryfire** [knadh/listmonk#982]
All providers send webhook notifications for abuse/spam complaints nowadays but there doesn’t seem to be an easy way to handle this in Listmonk.

What about adding a webhooks/abuse endpoint? The behaviour could be that any user reported via this endpoint is added to the blocklist, and the reason for the block (abuse) is recorded. Perhaps a new db field “block_reason” could be added to capture this kind of info.

**Comment by binaryfire** [comment]
The auto blocking and “block_reason” behaviour could be extended to “hard” bounces too (as an optional setting we can enable).

Amazon reduces your reputation if you keep trying to resend to dead email addresses so it’s import to avoid that

**Comment by knadh** [comment]
Bounce type + additional metadata is already supported and these fields are recorded for SES bounces. Do the big e-mail providers send separate webhook POSTs for abuse reports? Or do they tend to be the same as bounce reports?

**Comment by binaryfire** [comment]
Sorry, I removed SES from the title for clarity. I’m talking about the generic webhook endpoint for unsupported providers.

Each provider handles things differently. Amazon can separate events into separate SNS notifications: https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html. But they can be sent to the same endpoint if you choose. 

Sendgrid and Elastic bundles everything into a single “events” webhook.

According to the docs, the /webhooks/bounce endpoint only has “soft” and “hard” as types. Would it be possible to add “complaint” as a third type and have a setting which auto-blocks “hard” and “complaint” bounces?

**Comment by knadh** [comment]
Is `complaint` reasonably universal amongst providers? If yes, we can consider adding it.

**Comment by binaryfire** [comment]
@knadh Yes very universal. I don’t know of any major provider that doesn’t have it.

**Comment by MaximilianKohler** [comment]
@knadh not sure if I should make a new issue for this but it seems the latest listmonk update updated & broke something to do with this?

I just so happened to notice that one of my subscribers who made an abuse complaint didn't get automatically added to the Listmonk block list. I looked at the listmonk logs and I see a bunch of:

>error processing SES notification: notification type is not bounce

It seems this started happening after the listmonk update. I haven't changed anything in SES. And I check SES and it's still registering them on their internal blocklist. 

I'm not seeing any new setting in `/admin/settings` that I would need to change.

**Comment by binaryfire** [comment]
I agree with @Seneral re: treating soft bounces differently. We ended up not using Listmonk because of that issue.

**Comment by Seneral** [comment]
> I agree with @Seneral re: treating soft bounces differently. We ended up not using Listmonk because of that issue.

Once I do figure this out it's an easy enough fix, looking at the code. So will likely do it at some point

**Comment by justinh-rahb** [comment]
Possibly related? #1270

**Comment by knadh** [comment]
Ouch. This is a bug from a PR that was merged in the last release . I've just pushed a fix https://github.com/knadh/listmonk/commit/b433ef68ec47b3e411488f84bc12a43831a64936

An RC build with this fix is available here `listmonk/listmonk:rc-2.4.1` if you're using a Docker installation of listmonk.

**Comment by Seneral** [comment]
Unfortunately I still get the same error, it seems SES sends something other than "" and "Bounce".
`error processing SES notification: notification type is not bounce` with the proper rc-version `v2.4.0 (b433ef6 2023-04-02T15:13:14Z)`
If you can tell me what could be wrong with my local dev setup (no admin pages, despite it asking for the password), I might be able to test it myself

**Comment by knadh** [comment]
@Seneral could you please run this debug version (`listmonk/listmonk:rc-2.4.1-debug`) that prints the JSON payload from SES to stdout and share the payload here.

**Comment by Seneral** [comment]
Hm, pulling did download something, but the logs say `v2.4.0 (b433ef6 2023-04-02T17:06:29Z)` (same commit, but newer timestamp), but the output didn't change. Not sure if the same commit id means code is the same, or if it didn't pull properly because of that

**Comment by Seneral** [comment]
Mb, it didn't show up in the UI logs, only in the docker logs:
`"notificationType":"Complaint","complaint":{"feedbackId":"0110018742fe9d61-7b1091e5-d90e-4900-be29-1077a400102a-000000","complaintSubType":null,"complainedRecipients":[{"emailAddress":"complaint@simulator.amazonses.com"}],"timestamp":"2023-04-02T17:23:15.000Z","userAgent":"Amazon SES Mailbox Simulator","complaintFeedbackType":"abuse"`
etc

**Comment by knadh** [comment]
Ah, `"notificationType": "Complaint"` isn't a "Bounce". Looks like support for complaint also has to be added, but we need to test the bounce notification.

**Comment by Seneral** [comment]
> Ah, `"notificationType": "Complaint"` isn't a "Bounce". Looks like support for complaint also has to be added, but we need to test the bounce notification.

Bounce is just normal:
```
{
    "notificationType": "Bounce",
    "bounce":
    {
        "feedbackId": "01100187464b66a0-0014c6f6-0342-4f7e-91d8-aec7dfe537d0-000000",
        "bounceType": "Permanent",
        "bounceSubType": "General",
        "bouncedRecipients": [
        {
            "emailAddress": "suppressionlist@simulator.amazonses.com",
            "action": "failed",
            "status": "5.1.1",
            "diagnosticCode": "smtp; 550 5.1.1 user unknown ( blacklisted address: suppressionlist@simulator.amazonses.com )"
        }],
        "timestamp": "2023-04-03T08:45:59.000Z",
        "remoteMtaIp": "34.254.47.232",
        "reportingMTA": "dns; e240-9.smtp-out.eu-north-1.amazonses.com"
    },
    "mail":
    {
    }
}
```
So not sure what you mean. I believe complaint should just be treated as a hard bounce for the ses webhook.
Again would prefer soft bounces not block-listing emails, if I had dev mode working I might try that myself.

**Comment by binaryfire** [comment]
Personally I still think the best way to solve this would be to add a “complaint” type to Listmonk (in addition to bounce).

In Amazon’s case, anything with “notificationType": "Complaint" would be marked as “complaint” rather than “bounce” but it’d be treated the same way. I.e. mail wouldn’t be sent to those addresses.

Most of the big providers send complaint feedback and not being able to capture and view complaints in Listmonk was a big problem for us.

It’d be great if that was added.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/5fc28a733c7d6d9e6e3a2d4cc699e009c142bf35 adds support for per-bounce-type actions.

![image](https://user-images.githubusercontent.com/547147/231071354-565e6e8d-fe85-4956-bbf8-49eb3d7b0330.png)

**Comment by binaryfire** [comment]
Awesome!

**Comment by binaryfire** [comment]
Hi @knadh. Is it possible to specify the "complaint" type when using the generic webhook api endpoint? https://listmonk.app/docs/bounces/#webhook-api

At the moment the docs just say:

> type | String | Required | hard or soft bounce. Currently, this has no effect on how the bounce is treated.

Cheers

**Comment by knadh** [comment]
After the recent changes, `type = soft | hard | complaint` works. Will update the docs during the next release.

**Comment by MaximilianKohler** [comment]
> After the recent changes, `type = soft | hard | complaint` works. Will update the docs during the next release.

Do you have an estimate on when the update that fixes the `complaint` issue will be published? It's kind of urgent. I've been relying on email notifications (SES's `email feedback forwarding` option) and manually unsubscribing people who complain, but now I'm having some trouble with email notifications.
